apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # This must match the exposed port in your kind config
